version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: inbox
      POSTGRES_PASSWORD: inbox
      POSTGRES_DB: inbox_detox
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
