services:
  - type: web
    name: inbox-detox
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: inbox-detox-db
          property: connectionString

databases:
  - name: inbox-detox-db
    databaseName: inbox_detox
    user: inbox_detox_user