"""add email_content to email_analytics

Revision ID: 898d54edd068
Revises: '7be1a575e101'
Create Date: 2025-10-10 00:26:14.118069

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898d54edd068'
down_revision = '7be1a575e101'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_analytics', sa.Column('email_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_analytics', 'email_content')
    # ### end Alembic commands ###
